runtime:    java
env:        flex
threadsafe: false

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1  
resources:
  cpu: 1
  memory_gb: 6
env_variables:
  JAVA_OPTS: -Dcom.idrsolutions.useTempDir=true -Dcom.idrsolutions.defaultOutput=gcp
# [END appyaml]
